# © Designed and Developed by Mehmet Güdük.
# © Licensed with GPL-3.0 License, Author is Mehmet Güdük.



# The visual and design part of the application is here.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(400, 600))
        MainWindow.setMaximumSize(QtCore.QSize(400, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Icons/app2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget_MainApp = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget_MainApp.setGeometry(QtCore.QRect(0, 0, 401, 581))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.stackedWidget_MainApp.setFont(font)
        self.stackedWidget_MainApp.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.stackedWidget_MainApp.setToolTip("")
        self.stackedWidget_MainApp.setWhatsThis("")
        self.stackedWidget_MainApp.setStyleSheet("#page_2{\n"
"background-color: #394867;\n"
"}\n"
"#page{\n"
"background-color: #394867;\n"
"}\n"
"#page_4{\n"
"background-color: #394867;\n"
"}\n"
"#page_3{\n"
"background-color: #394867;\n"
"}\n"
"#page_5{\n"
"background-color: #394867;\n"
"}")
        self.stackedWidget_MainApp.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedWidget_MainApp.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stackedWidget_MainApp.setLineWidth(1)
        self.stackedWidget_MainApp.setObjectName("stackedWidget_MainApp")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.graphicsView = QtWidgets.QGraphicsView(self.page_3)
        self.graphicsView.setGeometry(QtCore.QRect(20, 80, 361, 81))
        self.graphicsView.setMaximumSize(QtCore.QSize(16777215, 90))
        self.graphicsView.setStyleSheet("border-image: url(:/icons/Icons/Başlıksız-1.jpg);\n"
"border-image: url(:/icons/Icons/Başlıksız-1.jpg);")
        self.graphicsView.setObjectName("graphicsView")
        self.label = QtWidgets.QLabel(self.page_3)
        self.label.setGeometry(QtCore.QRect(30, 170, 341, 271))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setWordWrap(True)
        self.label.setIndent(-1)
        self.label.setOpenExternalLinks(False)
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.page_3)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 420, 341, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_homepage_deckcars = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_homepage_deckcars.sizePolicy().hasHeightForWidth())
        self.btn_homepage_deckcars.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_homepage_deckcars.setFont(font)
        self.btn_homepage_deckcars.setStyleSheet("background-color: rgb(234, 254, 255);\n"
"color: rgb(246, 65, 108);")
        self.btn_homepage_deckcars.setObjectName("btn_homepage_deckcars")
        self.horizontalLayout_3.addWidget(self.btn_homepage_deckcars)
        self.btn_homepage_study = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_homepage_study.sizePolicy().hasHeightForWidth())
        self.btn_homepage_study.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_homepage_study.setFont(font)
        self.btn_homepage_study.setStyleSheet("background-color: rgb(234, 254, 255);\n"
"color: rgb(246, 65, 108);")
        self.btn_homepage_study.setObjectName("btn_homepage_study")
        self.horizontalLayout_3.addWidget(self.btn_homepage_study)
        self.label_2 = QtWidgets.QLabel(self.page_3)
        self.label_2.setGeometry(QtCore.QRect(0, 560, 401, 16))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.page_3)
        self.label_5.setGeometry(QtCore.QRect(30, 380, 331, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.label_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setScaledContents(False)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_5.setWordWrap(True)
        self.label_5.setIndent(-1)
        self.label_5.setOpenExternalLinks(False)
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.page_3)
        self.label_4.setGeometry(QtCore.QRect(30, 390, 251, 21))
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.page_3)
        self.label_6.setGeometry(QtCore.QRect(30, 350, 301, 21))
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.page_3)
        self.label_7.setGeometry(QtCore.QRect(30, 340, 331, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.label_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_7.setTextFormat(QtCore.Qt.AutoText)
        self.label_7.setScaledContents(False)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_7.setWordWrap(True)
        self.label_7.setIndent(-1)
        self.label_7.setOpenExternalLinks(False)
        self.label_7.setObjectName("label_7")
        self.stackedWidget_MainApp.addWidget(self.page_3)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.page)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(20, 20, 361, 191))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.typeDeckName = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.typeDeckName.setMinimumSize(QtCore.QSize(359, 22))
        self.typeDeckName.setStyleSheet("background-color: #eafeff;\n"
"color: black;\n"
"")
        self.typeDeckName.setFrame(False)
        self.typeDeckName.setObjectName("typeDeckName")
        self.gridLayout_3.addWidget(self.typeDeckName, 1, 0, 1, 1)
        self.listDeck = QtWidgets.QListWidget(self.gridLayoutWidget_4)
        self.listDeck.setStyleSheet("background-color: #F9F7F7;\n"
"")
        self.listDeck.setFrameShape(QtWidgets.QFrame.Box)
        self.listDeck.setFrameShadow(QtWidgets.QFrame.Plain)
        self.listDeck.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.listDeck.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listDeck.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listDeck.setProperty("showDropIndicator", False)
        self.listDeck.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.listDeck.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.listDeck.setObjectName("listDeck")
        self.gridLayout_3.addWidget(self.listDeck, 0, 0, 1, 1)
        self.gridLayout_1 = QtWidgets.QGridLayout()
        self.gridLayout_1.setObjectName("gridLayout_1")
        self.btnCreateDeck = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btnCreateDeck.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btnCreateDeck.setStyleSheet("background-color: rgb(246, 65, 108);\n"
"color: black;")
        self.btnCreateDeck.setAutoDefault(False)
        self.btnCreateDeck.setDefault(False)
        self.btnCreateDeck.setFlat(False)
        self.btnCreateDeck.setObjectName("btnCreateDeck")
        self.gridLayout_1.addWidget(self.btnCreateDeck, 0, 0, 1, 1)
        self.btnSortDecks = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btnSortDecks.setStyleSheet("background-color: rgb(246, 65, 108);\n"
"color: black;")
        self.btnSortDecks.setObjectName("btnSortDecks")
        self.gridLayout_1.addWidget(self.btnSortDecks, 0, 3, 1, 1)
        self.btnDeleteDeck = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btnDeleteDeck.setStyleSheet("background-color: rgb(246, 65, 108);\n"
"color: black;")
        self.btnDeleteDeck.setObjectName("btnDeleteDeck")
        self.gridLayout_1.addWidget(self.btnDeleteDeck, 0, 2, 1, 1)
        self.btnRenameDeck = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        self.btnRenameDeck.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btnRenameDeck.setStyleSheet("background-color: rgb(246, 65, 108);\n"
"color: black;\n"
"")
        self.btnRenameDeck.setObjectName("btnRenameDeck")
        self.gridLayout_1.addWidget(self.btnRenameDeck, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_1, 2, 0, 1, 1)
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.page)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(20, 220, 361, 341))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tableCards = QtWidgets.QTableWidget(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableCards.sizePolicy().hasHeightForWidth())
        self.tableCards.setSizePolicy(sizePolicy)
        self.tableCards.setStyleSheet("background-color: #F9F7F7;\n"
"")
        self.tableCards.setFrameShape(QtWidgets.QFrame.Box)
        self.tableCards.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableCards.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableCards.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableCards.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableCards.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.tableCards.setTabKeyNavigation(False)
        self.tableCards.setProperty("showDropIndicator", False)
        self.tableCards.setDragDropOverwriteMode(False)
        self.tableCards.setAlternatingRowColors(True)
        self.tableCards.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableCards.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableCards.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableCards.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableCards.setShowGrid(True)
        self.tableCards.setWordWrap(True)
        self.tableCards.setCornerButtonEnabled(False)
        self.tableCards.setObjectName("tableCards")
        self.tableCards.setColumnCount(2)
        self.tableCards.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableCards.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableCards.setHorizontalHeaderItem(1, item)
        self.tableCards.horizontalHeader().setCascadingSectionResizes(False)
        self.tableCards.horizontalHeader().setDefaultSectionSize(171)
        self.tableCards.horizontalHeader().setHighlightSections(True)
        self.tableCards.horizontalHeader().setMinimumSectionSize(39)
        self.tableCards.horizontalHeader().setSortIndicatorShown(True)
        self.tableCards.horizontalHeader().setStretchLastSection(False)
        self.tableCards.verticalHeader().setVisible(False)
        self.tableCards.verticalHeader().setCascadingSectionResizes(False)
        self.tableCards.verticalHeader().setHighlightSections(False)
        self.tableCards.verticalHeader().setSortIndicatorShown(False)
        self.tableCards.verticalHeader().setStretchLastSection(False)
        self.gridLayout_4.addWidget(self.tableCards, 0, 0, 1, 2)
        self.btnDeleteCard = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.btnDeleteCard.setStyleSheet("background-color: rgb(246, 65, 108);\n"
"color: black;")
        self.btnDeleteCard.setObjectName("btnDeleteCard")
        self.gridLayout_4.addWidget(self.btnDeleteCard, 2, 1, 1, 1)
        self.btnCreateCard = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.btnCreateCard.setStyleSheet("background-color: rgb(246, 65, 108);\n"
"color: black;")
        self.btnCreateCard.setObjectName("btnCreateCard")
        self.gridLayout_4.addWidget(self.btnCreateCard, 2, 0, 1, 1)
        self.stackedWidget_MainApp.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.page_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 20, 361, 544))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.comboBox_deck_select = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBox_deck_select.setMinimumSize(QtCore.QSize(0, 20))
        self.comboBox_deck_select.setStyleSheet("#comboBox_deck_select{\n"
"background-color: #eafeff;\n"
"color: black;\n"
"}")
        self.comboBox_deck_select.setFrame(True)
        self.comboBox_deck_select.setObjectName("comboBox_deck_select")
        self.gridLayout_2.addWidget(self.comboBox_deck_select, 0, 0, 1, 2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.btnBlue = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnBlue.sizePolicy().hasHeightForWidth())
        self.btnBlue.setSizePolicy(sizePolicy)
        self.btnBlue.setStyleSheet("background-color: #00a8d7;")
        self.btnBlue.setText("")
        self.btnBlue.setObjectName("btnBlue")
        self.gridLayout.addWidget(self.btnBlue, 1, 4, 1, 1)
        self.btnRed = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRed.sizePolicy().hasHeightForWidth())
        self.btnRed.setSizePolicy(sizePolicy)
        self.btnRed.setStyleSheet("background-color: #f3454d;")
        self.btnRed.setText("")
        self.btnRed.setObjectName("btnRed")
        self.gridLayout.addWidget(self.btnRed, 1, 0, 1, 1)
        self.btnYellow = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnYellow.sizePolicy().hasHeightForWidth())
        self.btnYellow.setSizePolicy(sizePolicy)
        self.btnYellow.setStyleSheet("background-color: rgb(255, 221, 0);")
        self.btnYellow.setText("")
        self.btnYellow.setObjectName("btnYellow")
        self.gridLayout.addWidget(self.btnYellow, 1, 2, 1, 1)
        self.btnOrange = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOrange.sizePolicy().hasHeightForWidth())
        self.btnOrange.setSizePolicy(sizePolicy)
        self.btnOrange.setStyleSheet("background-color: rgb(255, 138, 71);")
        self.btnOrange.setText("")
        self.btnOrange.setObjectName("btnOrange")
        self.gridLayout.addWidget(self.btnOrange, 1, 1, 1, 1)
        self.btnGreen = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnGreen.sizePolicy().hasHeightForWidth())
        self.btnGreen.setSizePolicy(sizePolicy)
        self.btnGreen.setStyleSheet("background-color: #7fae2e;")
        self.btnGreen.setText("")
        self.btnGreen.setObjectName("btnGreen")
        self.gridLayout.addWidget(self.btnGreen, 1, 3, 1, 1)
        self.lcdNumber_Red = QtWidgets.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumber_Red.setObjectName("lcdNumber_Red")
        self.gridLayout.addWidget(self.lcdNumber_Red, 2, 0, 1, 1)
        self.lcdNumber_Orange = QtWidgets.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumber_Orange.setObjectName("lcdNumber_Orange")
        self.gridLayout.addWidget(self.lcdNumber_Orange, 2, 1, 1, 1)
        self.lcdNumber_Yellow = QtWidgets.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumber_Yellow.setObjectName("lcdNumber_Yellow")
        self.gridLayout.addWidget(self.lcdNumber_Yellow, 2, 2, 1, 1)
        self.lcdNumber_Green = QtWidgets.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumber_Green.setObjectName("lcdNumber_Green")
        self.gridLayout.addWidget(self.lcdNumber_Green, 2, 3, 1, 1)
        self.lcdNumber_Blue = QtWidgets.QLCDNumber(self.gridLayoutWidget_2)
        self.lcdNumber_Blue.setObjectName("lcdNumber_Blue")
        self.gridLayout.addWidget(self.lcdNumber_Blue, 2, 4, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 7, 0, 1, 4)
        self.btn_start_study = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_start_study.setMaximumSize(QtCore.QSize(50, 23))
        self.btn_start_study.setStyleSheet("background-color: rgb(246, 65, 108);\n"
"color: black;")
        self.btn_start_study.setObjectName("btn_start_study")
        self.gridLayout_2.addWidget(self.btn_start_study, 0, 2, 1, 1)
        self.btn_stop_studying = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_stop_studying.setMaximumSize(QtCore.QSize(50, 23))
        self.btn_stop_studying.setStyleSheet("background-color: rgb(246, 65, 108);\n"
"color: black;")
        self.btn_stop_studying.setObjectName("btn_stop_studying")
        self.gridLayout_2.addWidget(self.btn_stop_studying, 0, 3, 1, 1)
        self.label_shows_card_front = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_shows_card_front.sizePolicy().hasHeightForWidth())
        self.label_shows_card_front.setSizePolicy(sizePolicy)
        self.label_shows_card_front.setMinimumSize(QtCore.QSize(359, 190))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_shows_card_front.setFont(font)
        self.label_shows_card_front.setStyleSheet("background-color: #F9F7F7;\n"
"color: black;")
        self.label_shows_card_front.setFrameShape(QtWidgets.QFrame.Box)
        self.label_shows_card_front.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_shows_card_front.setText("")
        self.label_shows_card_front.setTextFormat(QtCore.Qt.RichText)
        self.label_shows_card_front.setScaledContents(False)
        self.label_shows_card_front.setAlignment(QtCore.Qt.AlignCenter)
        self.label_shows_card_front.setWordWrap(True)
        self.label_shows_card_front.setOpenExternalLinks(False)
        self.label_shows_card_front.setObjectName("label_shows_card_front")
        self.gridLayout_2.addWidget(self.label_shows_card_front, 2, 0, 1, 4)
        self.btnShow = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btnShow.setMinimumSize(QtCore.QSize(359, 25))
        self.btnShow.setWhatsThis("")
        self.btnShow.setStyleSheet("background-color: #f6416c;\n"
"color: black;")
        self.btnShow.setObjectName("btnShow")
        self.gridLayout_2.addWidget(self.btnShow, 5, 0, 1, 4)
        self.label_shows_card_back = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_shows_card_back.setMinimumSize(QtCore.QSize(359, 190))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.label_shows_card_back.setFont(font)
        self.label_shows_card_back.setStyleSheet("background-color: #F9F7F7;\n"
"color: black;")
        self.label_shows_card_back.setFrameShape(QtWidgets.QFrame.Box)
        self.label_shows_card_back.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_shows_card_back.setText("")
        self.label_shows_card_back.setTextFormat(QtCore.Qt.RichText)
        self.label_shows_card_back.setAlignment(QtCore.Qt.AlignCenter)
        self.label_shows_card_back.setWordWrap(True)
        self.label_shows_card_back.setObjectName("label_shows_card_back")
        self.gridLayout_2.addWidget(self.label_shows_card_back, 3, 0, 1, 4)
        self.progressBar = QtWidgets.QProgressBar(self.gridLayoutWidget_2)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setFormat("%p%")
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_2.addWidget(self.progressBar, 1, 0, 1, 4)
        self.label_3 = QtWidgets.QLabel(self.page_2)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 401, 21))
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.stackedWidget_MainApp.addWidget(self.page_2)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.page_4)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(20, 62, 361, 501))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.textEdit_creation_back = QtWidgets.QTextEdit(self.gridLayoutWidget_6)
        self.textEdit_creation_back.setMaximumSize(QtCore.QSize(359, 60))
        self.textEdit_creation_back.setTabletTracking(False)
        self.textEdit_creation_back.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.textEdit_creation_back.setStyleSheet("background-color: #F9F7F7;\n"
"color: black;")
        self.textEdit_creation_back.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit_creation_back.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textEdit_creation_back.setTabChangesFocus(True)
        self.textEdit_creation_back.setObjectName("textEdit_creation_back")
        self.gridLayout_5.addWidget(self.textEdit_creation_back, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_add_the_card_below = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.btn_add_the_card_below.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btn_add_the_card_below.setToolTip("")
        self.btn_add_the_card_below.setStyleSheet("background-color: rgb(246, 65, 108);\n"
"color: black;")
        self.btn_add_the_card_below.setObjectName("btn_add_the_card_below")
        self.horizontalLayout_2.addWidget(self.btn_add_the_card_below)
        self.btn_creation_clear = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.btn_creation_clear.setStyleSheet("background-color: rgb(246, 65, 108);\n"
"color: black;")
        self.btn_creation_clear.setObjectName("btn_creation_clear")
        self.horizontalLayout_2.addWidget(self.btn_creation_clear)
        self.gridLayout_5.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.tableWidget_creation_card_list = QtWidgets.QTableWidget(self.gridLayoutWidget_6)
        self.tableWidget_creation_card_list.setStyleSheet("background-color: #F9F7F7;\n"
"color: black;")
        self.tableWidget_creation_card_list.setFrameShape(QtWidgets.QFrame.Box)
        self.tableWidget_creation_card_list.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget_creation_card_list.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget_creation_card_list.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_creation_card_list.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.tableWidget_creation_card_list.setProperty("showDropIndicator", False)
        self.tableWidget_creation_card_list.setDragDropOverwriteMode(False)
        self.tableWidget_creation_card_list.setAlternatingRowColors(True)
        self.tableWidget_creation_card_list.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_creation_card_list.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_creation_card_list.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_creation_card_list.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_creation_card_list.setWordWrap(False)
        self.tableWidget_creation_card_list.setCornerButtonEnabled(False)
        self.tableWidget_creation_card_list.setObjectName("tableWidget_creation_card_list")
        self.tableWidget_creation_card_list.setColumnCount(2)
        self.tableWidget_creation_card_list.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_creation_card_list.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_creation_card_list.setHorizontalHeaderItem(1, item)
        self.tableWidget_creation_card_list.horizontalHeader().setDefaultSectionSize(181)
        self.tableWidget_creation_card_list.verticalHeader().setVisible(False)
        self.gridLayout_5.addWidget(self.tableWidget_creation_card_list, 3, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_creation_add_all_to_the_deck = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.btn_creation_add_all_to_the_deck.setStyleSheet("background-color: rgb(246, 65, 108);\n"
"color: black;")
        self.btn_creation_add_all_to_the_deck.setObjectName("btn_creation_add_all_to_the_deck")
        self.horizontalLayout.addWidget(self.btn_creation_add_all_to_the_deck)
        self.btn_creation_remove_card = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.btn_creation_remove_card.setStyleSheet("background-color: rgb(246, 65, 108);\n"
"color: black;")
        self.btn_creation_remove_card.setObjectName("btn_creation_remove_card")
        self.horizontalLayout.addWidget(self.btn_creation_remove_card)
        self.btn_creation_cancel = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        self.btn_creation_cancel.setStyleSheet("background-color: rgb(246, 65, 108);\n"
"color: black;")
        self.btn_creation_cancel.setObjectName("btn_creation_cancel")
        self.horizontalLayout.addWidget(self.btn_creation_cancel)
        self.gridLayout_5.addLayout(self.horizontalLayout, 4, 0, 1, 1)
        self.textEdit_creation_front = QtWidgets.QTextEdit(self.gridLayoutWidget_6)
        self.textEdit_creation_front.setMaximumSize(QtCore.QSize(359, 60))
        self.textEdit_creation_front.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.textEdit_creation_front.setStyleSheet("background-color: #F9F7F7;\n"
"color: black;")
        self.textEdit_creation_front.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit_creation_front.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textEdit_creation_front.setTabChangesFocus(True)
        self.textEdit_creation_front.setAcceptRichText(True)
        self.textEdit_creation_front.setObjectName("textEdit_creation_front")
        self.gridLayout_5.addWidget(self.textEdit_creation_front, 0, 0, 1, 1)
        self.lbl_title_creation_cardname = QtWidgets.QLabel(self.page_4)
        self.lbl_title_creation_cardname.setGeometry(QtCore.QRect(20, 20, 359, 35))
        self.lbl_title_creation_cardname.setMinimumSize(QtCore.QSize(350, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.lbl_title_creation_cardname.setFont(font)
        self.lbl_title_creation_cardname.setStyleSheet("background-color: #eafeff;")
        self.lbl_title_creation_cardname.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_title_creation_cardname.setText("")
        self.lbl_title_creation_cardname.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_title_creation_cardname.setObjectName("lbl_title_creation_cardname")
        self.stackedWidget_MainApp.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.tableWidget_for_records = QtWidgets.QTableWidget(self.page_5)
        self.tableWidget_for_records.setGeometry(QtCore.QRect(20, 60, 361, 181))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.tableWidget_for_records.setFont(font)
        self.tableWidget_for_records.setStyleSheet("background-color: #F9F7F7;\n"
"color: black;")
        self.tableWidget_for_records.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_for_records.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_for_records.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_for_records.setProperty("showDropIndicator", False)
        self.tableWidget_for_records.setDragDropOverwriteMode(False)
        self.tableWidget_for_records.setAlternatingRowColors(True)
        self.tableWidget_for_records.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_for_records.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_for_records.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_for_records.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_for_records.setWordWrap(True)
        self.tableWidget_for_records.setCornerButtonEnabled(False)
        self.tableWidget_for_records.setColumnCount(3)
        self.tableWidget_for_records.setObjectName("tableWidget_for_records")
        self.tableWidget_for_records.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_for_records.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_for_records.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_for_records.setHorizontalHeaderItem(2, item)
        self.tableWidget_for_records.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_for_records.horizontalHeader().setDefaultSectionSize(179)
        self.tableWidget_for_records.horizontalHeader().setMinimumSectionSize(39)
        self.tableWidget_for_records.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget_for_records.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_for_records.verticalHeader().setVisible(False)
        self.tableWidget_for_records.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget_for_records.verticalHeader().setDefaultSectionSize(23)
        self.tableWidget_for_records.verticalHeader().setHighlightSections(False)
        self.tableWidget_for_records.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget_for_records.verticalHeader().setStretchLastSection(False)
        self.dateTimeEdit_for_statistics = QtWidgets.QDateTimeEdit(self.page_5)
        self.dateTimeEdit_for_statistics.setGeometry(QtCore.QRect(20, 20, 361, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.dateTimeEdit_for_statistics.setFont(font)
        self.dateTimeEdit_for_statistics.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.dateTimeEdit_for_statistics.setStyleSheet("background-color: #eafeff;\n"
"color: rgb(246, 65, 108);")
        self.dateTimeEdit_for_statistics.setWrapping(False)
        self.dateTimeEdit_for_statistics.setFrame(True)
        self.dateTimeEdit_for_statistics.setAlignment(QtCore.Qt.AlignCenter)
        self.dateTimeEdit_for_statistics.setReadOnly(False)
        self.dateTimeEdit_for_statistics.setCalendarPopup(True)
        self.dateTimeEdit_for_statistics.setObjectName("dateTimeEdit_for_statistics")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.page_5)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 240, 361, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_clear_day = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.btn_clear_day.setStyleSheet("background-color: rgb(246, 65, 108);\n"
"color: black;")
        self.btn_clear_day.setObjectName("btn_clear_day")
        self.horizontalLayout_4.addWidget(self.btn_clear_day)
        self.btn_log_record = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.btn_log_record.setStyleSheet("background-color: rgb(246, 65, 108);\n"
"color: black;")
        self.btn_log_record.setObjectName("btn_log_record")
        self.horizontalLayout_4.addWidget(self.btn_log_record)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.page_5)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(20, 290, 361, 25))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.comboBox_for_statistic = QtWidgets.QComboBox(self.horizontalLayoutWidget_3)
        self.comboBox_for_statistic.setMinimumSize(QtCore.QSize(0, 20))
        self.comboBox_for_statistic.setStyleSheet("background-color: #eafeff;\n"
"color: rgb(246, 65, 108);")
        self.comboBox_for_statistic.setCurrentText("")
        self.comboBox_for_statistic.setFrame(True)
        self.comboBox_for_statistic.setObjectName("comboBox_for_statistic")
        self.horizontalLayout_5.addWidget(self.comboBox_for_statistic)
        self.btnSortDecks_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.btnSortDecks_2.setStyleSheet("background-color: rgb(246, 65, 108);\n"
"color: black;")
        self.btnSortDecks_2.setObjectName("btnSortDecks_2")
        self.horizontalLayout_5.addWidget(self.btnSortDecks_2)
        self.horizontalLayout_5.setStretch(0, 75)
        self.horizontalLayout_5.setStretch(1, 25)
        self.gridLayoutWidget = QtWidgets.QWidget(self.page_5)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 320, 361, 111))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lbl_orange_count = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_orange_count.setFont(font)
        self.lbl_orange_count.setStyleSheet("border-image: url(:/icons/Icons/syellow.jpg);")
        self.lbl_orange_count.setText("")
        self.lbl_orange_count.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_orange_count.setObjectName("lbl_orange_count")
        self.gridLayout_6.addWidget(self.lbl_orange_count, 0, 2, 1, 1)
        self.lbl_blue_count = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_blue_count.setFont(font)
        self.lbl_blue_count.setStyleSheet("border-image: url(:/icons/Icons/sblue.jpg);")
        self.lbl_blue_count.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_blue_count.setText("")
        self.lbl_blue_count.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_blue_count.setObjectName("lbl_blue_count")
        self.gridLayout_6.addWidget(self.lbl_blue_count, 0, 4, 1, 1)
        self.lbl_red_count = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_red_count.setFont(font)
        self.lbl_red_count.setStyleSheet("border-image: url(:/icons/Icons/sred.jpg);")
        self.lbl_red_count.setText("")
        self.lbl_red_count.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_red_count.setObjectName("lbl_red_count")
        self.gridLayout_6.addWidget(self.lbl_red_count, 0, 0, 1, 1)
        self.lbl_green_count = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_green_count.setFont(font)
        self.lbl_green_count.setStyleSheet("border-image: url(:/icons/Icons/sgreen.jpg);")
        self.lbl_green_count.setText("")
        self.lbl_green_count.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_green_count.setObjectName("lbl_green_count")
        self.gridLayout_6.addWidget(self.lbl_green_count, 0, 3, 1, 1)
        self.lbl_yellow_count = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_yellow_count.setFont(font)
        self.lbl_yellow_count.setStyleSheet("border-image: url(:/icons/Icons/sorange.jpg);")
        self.lbl_yellow_count.setText("")
        self.lbl_yellow_count.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_yellow_count.setObjectName("lbl_yellow_count")
        self.gridLayout_6.addWidget(self.lbl_yellow_count, 0, 1, 1, 1)
        self.lbl_total_count = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_total_count.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_total_count.setFont(font)
        self.lbl_total_count.setStyleSheet("border-image: url(:/icons/Icons/stotal.jpg);")
        self.lbl_total_count.setText("")
        self.lbl_total_count.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_total_count.setObjectName("lbl_total_count")
        self.gridLayout_6.addWidget(self.lbl_total_count, 0, 5, 1, 1)
        self.tableWidget_for_total_studied = QtWidgets.QTableWidget(self.page_5)
        self.tableWidget_for_total_studied.setGeometry(QtCore.QRect(20, 440, 361, 53))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_for_total_studied.sizePolicy().hasHeightForWidth())
        self.tableWidget_for_total_studied.setSizePolicy(sizePolicy)
        self.tableWidget_for_total_studied.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget_for_total_studied.setStyleSheet("background-color: #F9F7F7;\n"
"color: black;")
        self.tableWidget_for_total_studied.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget_for_total_studied.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_for_total_studied.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_for_total_studied.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_for_total_studied.setDragDropOverwriteMode(False)
        self.tableWidget_for_total_studied.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget_for_total_studied.setWordWrap(True)
        self.tableWidget_for_total_studied.setCornerButtonEnabled(False)
        self.tableWidget_for_total_studied.setObjectName("tableWidget_for_total_studied")
        self.tableWidget_for_total_studied.setColumnCount(1)
        self.tableWidget_for_total_studied.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_for_total_studied.setHorizontalHeaderItem(0, item)
        self.tableWidget_for_total_studied.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_for_total_studied.horizontalHeader().setDefaultSectionSize(50)
        self.tableWidget_for_total_studied.horizontalHeader().setHighlightSections(True)
        self.tableWidget_for_total_studied.horizontalHeader().setMinimumSectionSize(20)
        self.tableWidget_for_total_studied.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_for_total_studied.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_for_total_studied.verticalHeader().setVisible(False)
        self.tableWidget_for_total_studied.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget_for_total_studied.verticalHeader().setHighlightSections(True)
        self.tableWidget_for_last_studied = QtWidgets.QTableWidget(self.page_5)
        self.tableWidget_for_last_studied.setGeometry(QtCore.QRect(20, 500, 361, 53))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_for_last_studied.sizePolicy().hasHeightForWidth())
        self.tableWidget_for_last_studied.setSizePolicy(sizePolicy)
        self.tableWidget_for_last_studied.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget_for_last_studied.setStyleSheet("background-color: #F9F7F7;\n"
"color: black;")
        self.tableWidget_for_last_studied.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget_for_last_studied.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_for_last_studied.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_for_last_studied.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_for_last_studied.setDragDropOverwriteMode(False)
        self.tableWidget_for_last_studied.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget_for_last_studied.setWordWrap(True)
        self.tableWidget_for_last_studied.setCornerButtonEnabled(False)
        self.tableWidget_for_last_studied.setObjectName("tableWidget_for_last_studied")
        self.tableWidget_for_last_studied.setColumnCount(1)
        self.tableWidget_for_last_studied.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_for_last_studied.setHorizontalHeaderItem(0, item)
        self.tableWidget_for_last_studied.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_for_last_studied.horizontalHeader().setDefaultSectionSize(50)
        self.tableWidget_for_last_studied.horizontalHeader().setHighlightSections(True)
        self.tableWidget_for_last_studied.horizontalHeader().setMinimumSectionSize(20)
        self.tableWidget_for_last_studied.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_for_last_studied.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_for_last_studied.verticalHeader().setVisible(False)
        self.tableWidget_for_last_studied.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget_for_last_studied.verticalHeader().setHighlightSections(True)
        self.stackedWidget_MainApp.addWidget(self.page_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMaximumSize(QtCore.QSize(16777215, 22))
        self.toolBar.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.toolBar.setStyleSheet("background-color: #F9F7F7;")
        self.toolBar.setMovable(False)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionStudy = QtWidgets.QAction(MainWindow)
        self.actionStudy.setObjectName("actionStudy")
        self.actionHomePage = QtWidgets.QAction(MainWindow)
        self.actionHomePage.setObjectName("actionHomePage")
        self.actionDeckandCard = QtWidgets.QAction(MainWindow)
        self.actionDeckandCard.setObjectName("actionDeckandCard")
        self.actionStatistics = QtWidgets.QAction(MainWindow)
        self.actionStatistics.setObjectName("actionStatistics")
        self.toolBar.addAction(self.actionHomePage)
        self.toolBar.addAction(self.actionDeckandCard)
        self.toolBar.addAction(self.actionStudy)
        self.toolBar.addAction(self.actionStatistics)

        self.retranslateUi(MainWindow)
        self.stackedWidget_MainApp.setCurrentIndex(0)
        self.comboBox_for_statistic.setCurrentIndex(-1)
        self.listDeck.currentTextChanged['QString'].connect(self.typeDeckName.setText)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LEARNQUICK"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">LearnQuick</span> is a flashcard application that you can create your own deck, add cards into deck and study.</p><p>The main function of LearnQuick is to help the user memorize things. User will create the cards with the sides front and back. Front side will be the question, and back side will be the answer. After the desired number of cards, a deck is completed, for example: Physics deck. While studying deck, cards will be shown one by one and user has to guess the back side, the answer, and rate the difficulty of the card. The frequency of how often which cards will be shown to user is determined by the difficulty rating of the cards. More difficult cards will be shown more often and vice versa.</p></body></html>"))
        self.btn_homepage_deckcars.setText(_translate("MainWindow", "Deck and Cards"))
        self.btn_homepage_study.setText(_translate("MainWindow", "Study"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:7pt; color:#ffffff;\">© Designed and Developed by Mehmet Güdük</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p>Do you want to help me to improve this application ?<span style=\" color:#f6416c;\"><br/></span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><a href=\"mailto:mehmetguduk98@gmail.com?subject=LearnQuick\"><span style=\" font-weight:600; text-decoration: underline; color:#f6416c;\">Click here and send me an email</span></a></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><a href=\"https://github.com/mehmetguduk/LearnQuick\"><span style=\" font-weight:600; text-decoration: underline; color:#f6416c;\">Click here for more info about how LearnQuick works</span></a></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p>Do you want to learn more?<span style=\" color:#f6416c;\"><br/></span></p></body></html>"))
        self.typeDeckName.setPlaceholderText(_translate("MainWindow", "Type deck name here"))
        self.btnCreateDeck.setText(_translate("MainWindow", "Create deck"))
        self.btnSortDecks.setText(_translate("MainWindow", "Sort decks"))
        self.btnDeleteDeck.setText(_translate("MainWindow", "Delete deck"))
        self.btnRenameDeck.setText(_translate("MainWindow", "Rename deck"))
        self.tableCards.setSortingEnabled(True)
        item = self.tableCards.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Front"))
        item = self.tableCards.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Back"))
        self.btnDeleteCard.setText(_translate("MainWindow", "Delete card"))
        self.btnCreateCard.setText(_translate("MainWindow", "Create card"))
        self.btnBlue.setToolTip(_translate("MainWindow", "Shortcut : 5"))
        self.btnBlue.setShortcut(_translate("MainWindow", "5"))
        self.btnRed.setToolTip(_translate("MainWindow", "Shorcut : 1"))
        self.btnRed.setShortcut(_translate("MainWindow", "1"))
        self.btnYellow.setToolTip(_translate("MainWindow", "Shortcut : 3"))
        self.btnYellow.setShortcut(_translate("MainWindow", "3"))
        self.btnOrange.setToolTip(_translate("MainWindow", "Shorcut : 2"))
        self.btnOrange.setShortcut(_translate("MainWindow", "2"))
        self.btnGreen.setToolTip(_translate("MainWindow", "Shortcut : 4"))
        self.btnGreen.setShortcut(_translate("MainWindow", "4"))
        self.btn_start_study.setText(_translate("MainWindow", "Start"))
        self.btn_stop_studying.setText(_translate("MainWindow", "Stop"))
        self.btnShow.setToolTip(_translate("MainWindow", "Shortcut : Space"))
        self.btnShow.setText(_translate("MainWindow", "Show"))
        self.btnShow.setShortcut(_translate("MainWindow", "Space"))
        self.textEdit_creation_back.setPlaceholderText(_translate("MainWindow", "Back"))
        self.btn_add_the_card_below.setText(_translate("MainWindow", "Add the card below"))
        self.btn_add_the_card_below.setShortcut(_translate("MainWindow", "Return"))
        self.btn_creation_clear.setText(_translate("MainWindow", "Clear"))
        self.tableWidget_creation_card_list.setSortingEnabled(True)
        item = self.tableWidget_creation_card_list.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Front"))
        item = self.tableWidget_creation_card_list.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Back"))
        self.btn_creation_add_all_to_the_deck.setText(_translate("MainWindow", "Add all to the deck"))
        self.btn_creation_remove_card.setText(_translate("MainWindow", "Remove card"))
        self.btn_creation_cancel.setText(_translate("MainWindow", "Cancel"))
        self.textEdit_creation_front.setPlaceholderText(_translate("MainWindow", "Front"))
        self.tableWidget_for_records.setSortingEnabled(True)
        item = self.tableWidget_for_records.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Deck name"))
        item = self.tableWidget_for_records.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Study time"))
        item = self.tableWidget_for_records.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "id"))
        self.dateTimeEdit_for_statistics.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy"))
        self.btn_clear_day.setText(_translate("MainWindow", "Clear day"))
        self.btn_log_record.setText(_translate("MainWindow", "Remove log"))
        self.btnSortDecks_2.setText(_translate("MainWindow", "Sort decks"))
        item = self.tableWidget_for_total_studied.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Total studied time"))
        item = self.tableWidget_for_last_studied.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Last studied time"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionStudy.setText(_translate("MainWindow", "Study"))
        self.actionHomePage.setText(_translate("MainWindow", "Home"))
        self.actionDeckandCard.setText(_translate("MainWindow", "Deck and Cards"))
        self.actionDeckandCard.setToolTip(_translate("MainWindow", "Deck and Cards"))
        self.actionStatistics.setText(_translate("MainWindow", "Statistics"))
        self.actionStatistics.setToolTip(_translate("MainWindow", "Statistics"))
import images